### ISSUE TITLE
TypeError: tuple indices must be integers or slices, not str

### ISSUE THREAD

**Issue by AIisCool** [csjliang/DASR#1]
`  File "C:\DASR\basicsr\test.py", line 45, in <module>
    test_pipeline(root_path)
  File "C:\DASR\basicsr\test.py", line 19, in test_pipeline
    make_exp_dirs(opt)
  File "C:\Python39\lib\site-packages\basicsr\utils\dist_util.py", line 80, in wrapper
    return func(*args, **kwargs)
  File "C:\Python39\lib\site-packages\basicsr\utils\misc.py", line 40, in make_exp_dirs
    path_opt = opt['path'].copy()
TypeError: tuple indices must be integers or slices, not str`

**Comment by csjliang** [comment]
Hi,

Thanks for your attention to our work. The code is validated on my Linux environment, please check if it is due to the mismatch of python packages or provide more information about the error. Thanks!

**Comment by zhangyunming** [comment]
same question

**Comment by csjliang** [comment]
> same question

Hi,

Could you please provide more information about this error? e.g., your environment. Or, is it possible for you to conduct the experiments on a Linux system? Thanks.

**Comment by zhangyunming** [comment]
ubuntu@ubuntu:/home/zhangyunming/DASR$ python basicsr/test.py -opt options/test/DASR/test_DASR.yml
Disable distributed.
Traceback (most recent call last):
  File "basicsr/test.py", line 45, in <module>
    test_pipeline(root_path)
  File "basicsr/test.py", line 19, in test_pipeline
    make_exp_dirs(opt)
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/basicsr/utils/dist_util.py", line 80, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/lib/python3.8/site-packages/basicsr/utils/misc.py", line 40, in make_exp_dirs
    path_opt = opt['path'].copy()
TypeError: tuple indices must be integers or slices, not str
ubuntu@ubuntu:/home/zhangyunming/DASR$ 

torch 1.9.0
ubuntu 18.04

**Comment by csjliang** [comment]
Hi,

Thanks for your information. Please follow our instructions by adding **PYTHONPATH="./:${PYTHONPATH}"** before the command line. Thanks.

**Comment by zhangyunming** [comment]
it is ok.  thank you

why add PYTHONPATH="./:${PYTHONPATH}"?

**Comment by csjliang** [comment]
> it is ok. thank you
> 
> why add PYTHONPATH="./:${PYTHONPATH}"?

It specifies the work dir, as there are many relative paths in our code. Thanks.
