### ISSUE TITLE
DF2Kmultiscale+OST_sub

### ISSUE THREAD

**Issue by Lucien66** [csjliang/DASR#11]
Hi! I have some questions about DF2Kmultiscale+OST_sub dataset. When i ran the script extract_subimages.py. The script stopped with no errors, with the output being 'All processes done.  There are many images' resolution of OST smaller than the crop size 480, how do you deal with these small images?

**Comment by peylnog** [comment]
I also have a similar question, what is the file structure of the dataset and the specific code generation?
