### ISSUE TITLE
Pretrained model correspond to which degradation space subset?

### ISSUE THREAD

**Issue by g-moschetti** [csjliang/DASR#4]
Hi and thanks for sharing your interesting research! 
My question is related to the pretrained model:
- the pretrained model correspond to which degradation space? S_1, S_2 or S_3?
- Or does the pretrained model correspond to the training done for the parameters in the train_DASR.yml file? So all three degradation spaces with the given probability:
```
degree_list: ['weak_degrade_one_stage', 'standard_degrade_one_stage', 'severe_degrade_two_stage']
degree_prob: [0.3, 0.3, 0.4]
```

Would it be possible to share (if you have done it and if is possible) the pretrained model only for the degradation spaces separately, ie one model for `weak_degrade_one_stage`, one model for `standard_degrade_one_stage `and one model for `severe_degrade_two_stage`? 
Thanks!

**Comment by csjliang** [comment]
Hi, thanks for your question. The released model is trained using the train_DASR.yml file. Therefore, the degradation space covers all three degrees with the given probability. The last one is similar to the RealESRGAN, and the first and the second are mild and moderate ones, respectively. Actually, we aim to construct a wide yet balanced degradation space to mimic that in real applications. For more descriptions and analysis of the degradation space, please kindly refer to our paper. 

For your second question, sure. We have conducted experiments on the 'severe_degrade_two_stage' by using our DASR, and it outperforms the baseline method to a large extent on severely degraded inputs. However, such a model is naturally restricted to those inputs, and the performance drops when facing clean inputs. The other two cases are similar. Actually, the main contribution of our method is to adaptively construct the SR model according to the degradation of inputs, which can achieve good performance with efficiency. You can validate the performance of DASR on respective subspaces. Thanks!
