### ISSUE TITLE
suggestion for fixing the code to use multi GPU

### ISSUE THREAD

**Issue by anse3832** [csjliang/DASR#5]
When I tried to use multi GPU, the code shows an error
(Unfortunately, I didn't save the error massage. It is related to dimension error)

So, I fixed the code in DASR/dasr/models/DASR_model.py as below, and it works well.
( multiplying self.opt['num_gpu'] )
![image](https://user-images.githubusercontent.com/77471764/161906946-2c05fb3c-7a8e-4ddc-be56-14f7767f4bee.png)
![image](https://user-images.githubusercontent.com/77471764/161906996-59faedb7-2b74-47d3-940b-f27e6964b341.png)
![image](https://user-images.githubusercontent.com/77471764/161907050-71cc6418-3853-4e7a-bd57-31030a318de7.png)

Please check if my correction is adequate. Thanks!

**Comment by csjliang** [comment]
Hi,

Thanks for your question. As we use distributed parallel training, the data we prepared is for one single GPU. The pytorch will help us to prepare the data for all points in the world. In your modified implementation, I think it will report a dimension mismatch error when the world size is larger than 1.
