### ISSUE TITLE
testing datasets 

### ISSUE THREAD

**Issue by Lucien1996** [csjliang/DASR#9]
Hi, thank you for your work！
will testing image degradation code be published in the future?

**Comment by csjliang** [comment]
Hi, thanks for your attention to our work.

Do you mean the code for preparing the synthetic testing dataset?

**Comment by Lucien1996** [comment]
yes！Is it possible for you to post the code for preparing testing dataset? Is there any reason why you haven't test on datasets such as set5 and set14？

**Comment by csjliang** [comment]
I have uploaded the code for preparing the dataset, please check (in DASR/scripts). We have tested the performance on the Urban100 dataset, which shows similar observations to the results of DIV2K (We did not report the results for readability). You can synthetic the validation data and test the DASR by yourself if you are interested. Thanks.
